name: Ping_build_main

on:
  push:
    branches:    
      - main
    paths:
      - 'Frends.Community.AgentTools/**'
  workflow_dispatch:

jobs:
  build:
   runs-on: ubuntu-latest
   steps:
   - uses: actions/checkout@v4
   - name: Setup dotnet
     uses: actions/setup-dotnet@v3
     with:
       dotnet-version: '6.0.x'
   - name: Install dependencies
     working-directory: Frends.Community.AgentTools
     run: dotnet restore
   - name: Build
     working-directory: Frends.Community.AgentTools
     run: dotnet build
   - name: Test with the dotnet CLI
     working-directory: Frends.Community.AgentTools
     run: dotnet test
