name: Build and publish

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    name: Build on windows-latest
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: Build
      run: dotnet build
    
    - name: Test
      env:
        EXAMPLE_ENVIROMENT_VARIABLE:  ${{ secrets.NUGET_PUBLISH_TOKEN }}
      run: dotnet test
      
    - name: Pack release version of task
      run: dotnet pack --configuration Release 
      
    - name: Push NuGet package to the testfeed
      run: dotnet nuget push Frends.Community.AgentTools\bin\Release\*.nupkg  --api-key ${{ secrets.NUGET_PUBLISH_TOKEN  }} --source https://nuget.pkg.github.com/cellza/index.json --symbol-source https://nuget.pkg.github.com/cellza/index.json --skip-duplicate